name: odoo_rpc
description: Odoo RPC Client library for Dart with session changes tracking via steam.
version: 0.2.0
homepage: https://github.com/ERP-Ukraine/odoo-rpc-dart
repository: https://github.com/ERP-Ukraine/odoo-rpc-dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: '>=0.11.3 <0.13.0'
  uuid: ^2.0.2
  validators: ^2.0.0
  meta: ^1.2.3

dev_dependencies:
  test: ^1.3.0
  crypto: any
