name: odoo_rpc
description: Odoo RPC Client library for Dart with session changes tracking via steam.
version: 0.5.2
homepage: https://github.com/ERP-Ukraine/odoo-rpc-dart
repository: https://github.com/ERP-Ukraine/odoo-rpc-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^1.1.0
  crypto: ^3.0.0
  lints: ^2.1.1

dev_dependencies:
  test: ^1.16.5
